-- MySQL Script generated by MySQL Workbench
-- Wed Aug 16 16:49:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema rzik
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rzik
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rzik` DEFAULT CHARACTER SET utf8 ;
USE `rzik` ;

-- -----------------------------------------------------
-- Table `rzik`.`r_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rzik`.`r_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rzik`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rzik`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `r_roles_id` INT NOT NULL,
  `trackm` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_r_roles1_idx` (`r_roles_id` ASC),
  CONSTRAINT `fk_Users_r_roles1`
    FOREIGN KEY (`r_roles_id`)
    REFERENCES `rzik`.`r_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rzik`.`r_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rzik`.`r_genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rzik`.`Musics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rzik`.`Musics` (
  `id` INT NOT NULL,
  `titre` VARCHAR(45) NULL,
  `artiste` VARCHAR(45) NULL,
  `likes` INT NULL,
  `ecoute` INT NULL,
  `lentgth` INT NULL,
  `cover` VARCHAR(150) NULL,
  `compositeur` VARCHAR(45) NULL,
  `download` TINYINT NULL,
  `date_upload` DATETIME NULL,
  `date_creation` DATETIME NULL,
  `description` TEXT NULL,
  `file` VARCHAR(150) NULL,
  `explicit` TINYINT NULL,
  `r_genres_id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Musics_r_genres_idx` (`r_genres_id` ASC),
  INDEX `fk_Musics_Users1_idx` (`Users_id` ASC),
  CONSTRAINT `fk_Musics_r_genres`
    FOREIGN KEY (`r_genres_id`)
    REFERENCES `rzik`.`r_genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Musics_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `rzik`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rzik`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rzik`.`Comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NULL,
  `Musics_id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comments_Musics1_idx` (`Musics_id` ASC),
  INDEX `fk_Comments_Users1_idx` (`Users_id` ASC),
  CONSTRAINT `fk_Comments_Musics1`
    FOREIGN KEY (`Musics_id`)
    REFERENCES `rzik`.`Musics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `rzik`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rzik`.`Playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rzik`.`Playlists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `likes` INT NULL,
  `description` TEXT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Playlists_Users1_idx` (`Users_id` ASC),
  CONSTRAINT `fk_Playlists_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `rzik`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rzik`.`Playlists_Musics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rzik`.`Playlists_Musics` (
  `Playlists_id` INT NOT NULL,
  `Musics_id` INT NOT NULL,
  PRIMARY KEY (`Playlists_id`, `Musics_id`),
  INDEX `fk_Playlists_has_Musics_Musics1_idx` (`Musics_id` ASC),
  INDEX `fk_Playlists_has_Musics_Playlists1_idx` (`Playlists_id` ASC),
  CONSTRAINT `fk_Playlists_has_Musics_Playlists1`
    FOREIGN KEY (`Playlists_id`)
    REFERENCES `rzik`.`Playlists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlists_has_Musics_Musics1`
    FOREIGN KEY (`Musics_id`)
    REFERENCES `rzik`.`Musics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
